### ISSUE TITLE
Do you plan support for ESP32?

### ISSUE THREAD

**Issue by rado99** [linux-downey/BME680_4_In_1_Sensor_Drv#1]
Hello,
I view there is a libgoalsec.a file for the ESP32 platform ready. Are you plan integrating it with your library and to add support for IAQ meassurement for it? Thank you in advance.

**Comment by linux-downey** [comment]
Emmm...
Actually this library was developed by chip manufacturers.We will follow up,But we can't confirm when it will be completed.
downey.
