### ISSUE TITLE
Communication error on ESP32 

### ISSUE THREAD

**Issue by rado99** [linux-downey/BME680_4_In_1_Sensor_Drv#2]
I am trying to run the basic_config_state example on I2C protocol, but I receive error -2 or -37, depending on the right pinout. Can you give me any suggestions where to search the problem?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Does this problem still exist? If so, can you provide a reproducible environment?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
