### ISSUE TITLE
Error when compiling sample for NodemMCU

### ISSUE THREAD

**Issue by pczekalski** [linux-downey/BME680_4_In_1_Sensor_Drv#3]
When trying to compile basic.ino under PlatformIO, I'm getting the following errors:
`/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o):(.text._ZN4Bsec11beginCommonEv+0x0): undefined reference to `bsec_init'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o):(.text._ZN4Bsec11beginCommonEv+0x4): undefined reference to `bsec_get_version'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o): in function `Bsec::beginCommon()':
bsec.cpp:(.text._ZN4Bsec11beginCommonEv+0x13): undefined reference to `bsec_init'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: bsec.cpp:(.text._ZN4Bsec11beginCommonEv+0x1d): undefined reference to `bsec_get_version'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o):(.text._ZN4Bsec18updateSubscriptionEP21bsec_virtual_sensor_thf+0x0): undefined reference to `bsec_update_subscription'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o): in function `Bsec::updateSubscription(bsec_virtual_sensor_t*, unsigned char, float)':
bsec.cpp:(.text._ZN4Bsec18updateSubscriptionEP21bsec_virtual_sensor_thf+0x46): undefined reference to `bsec_update_subscription'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o):(.text._ZN4Bsec15readProcessDataEx19bsec_bme_settings_t+0x8): undefined reference to `bsec_do_steps'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o): in function `Bsec::readProcessData(long long, bsec_bme_settings_t)':
bsec.cpp:(.text._ZN4Bsec15readProcessDataEx19bsec_bme_settings_t+0xf8): undefined reference to `bsec_do_steps'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o):(.text._ZN4Bsec3runEv+0x4): undefined reference to `bsec_sensor_control'
/home/pczekalski/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/nodemcuv2/libc9c/libSeeed_BME680_V1-master.a(bsec.cpp.o): in function `Bsec::run()':
bsec.cpp:(.text._ZN4Bsec3runEv+0x48): undefined reference to `bsec_sensor_control'`

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Does this problem still exist? If so, can you provide the sketch you use?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
